### ISSUE TITLE
rendezvous serice crash with CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by p-j** [geekuillaume/soundsync#110]
Hi !
Thanks for this app, I've been using it for a couple of days but recently I've encountered this error:
```
● soundsync.service - soundsync
     Loaded: loaded (/etc/systemd/system/soundsync.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-10-07 13:24:43 CEST; 6h ago
   Main PID: 2911 (bash)
      Tasks: 28 (limit: 9265)
     Memory: 145.6M
     CGroup: /system.slice/soundsync.service
             ├─2911 bash /opt/Soundsync/soundsync --configDir /etc/soundsync
             ├─2919 pulseaudio
             └─2922 /opt/Soundsync/soundsync_electron --experimental-wasm-threads /opt/Soundsync/resources/app/index.js --configDir /etc/soundsync

oct. 07 19:42:54 nuc soundsync[2922]: 2021-10-07T17:42:54.790Z soundsync:rendezvous Registering to rendezvous service with: 192.168.1.117:6512_cf94eb0f-7294-434d-9805-a7c9f84f7c7b
oct. 07 19:42:54 nuc soundsync[2922]: 2021-10-07T17:42:54.866Z soundsync:rendezvous Error while registering, trying again in 1 minute Error: certificate has expired
oct. 07 19:42:54 nuc soundsync[2922]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)
oct. 07 19:42:54 nuc soundsync[2922]:     at TLSSocket.emit (events.js:310:20)
oct. 07 19:42:54 nuc soundsync[2922]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
oct. 07 19:42:54 nuc soundsync[2922]:     at TLSSocket._finishInit (_tls_wrap.js:927:8)
oct. 07 19:42:54 nuc soundsync[2922]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12) {
oct. 07 19:42:54 nuc soundsync[2922]:   code: 'CERT_HAS_EXPIRED',
oct. 07 19:42:54 nuc soundsync[2922]:   response: undefined
oct. 07 19:42:54 nuc soundsync[2922]: }
```

This instance is running on a up-to-date Ubuntu.
Once the Ubuntu is rebooted, at first I can start the service and have a Spotify Connect to send music to it, but after a while it disconnect and the stack trace above is in the log. 

Let me know if you need more details or if I can do anything to fix it on my end.

**Comment by geekuillaume** [comment]
This should be fixed with the latest version 0.4.16

**Comment by EricHier** [comment]
@p-j – did you find a solution to the 100% CPU utilization problem? I just did the upgrade and it works way less reliable now.

**Comment by p-j** [comment]
Unfortunately no and I haven't had much time to dig into it either.
