### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [geekuillaume/soundsync#111]
Error: Provided outputBuffer is too small: 11520 < 11744
    at SoxrResampler.processChunk (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\node_modules\wasm-audio-resampler\app\soxr_resampler.js:99:19)
    at AudioChunkStreamResampler.write (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\utils\audio\chunk_stream.js:254:44)
    at Yallist.<anonymous> (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:376:18)
    at Yallist.forEach (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\node_modules\yallist\yallist.js:156:8)
    at AudioChunkStream.emit (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:375:20)
    at AudioChunkStream.write (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at Timeout.AudioChunkStream._pushNecessaryChunks [as _onTimeout] (C:\Users\prajw\AppData\Local\Programs\soundsync\resources\app\utils\audio\chunk_stream.js:106:22)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by stuartmau** [comment]
me too.

"There has been an error with soundsync"

Error: Provided outputBuffer is too small: 11520 < 11744
    at SoxrResampler.processChunk (\soundsync\resources\app\node_modules\wasm-audio-resampler\app\soxr_resampler.js:99:19)
    at AudioChunkStreamResampler.write (\soundsync\resources\app\utils\audio\chunk_stream.js:254:44)
    at Yallist.<anonymous> (\soundsync\resources\app\node_modules\minipass\index.js:376:18)
    at Yallist.forEach (\soundsync\resources\app\node_modules\minipass\node_modules\yallist\yallist.js:156:8)
    at AudioChunkStream.emit (\soundsync\resources\app\node_modules\minipass\index.js:375:20)
    at AudioChunkStream.write (\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at Timeout.AudioChunkStream._pushNecessaryChunks [as _onTimeout] (\soundsync\resources\app\utils\audio\chunk_stream.js:106:22)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

I selected an old webcam as the input on a win10 pc.

Clicking OK closes the box but it immediately is triggered again. Mashing the close button eventually kills the app. Restarting immediately triggers the error.
