### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by Yersi88** [geekuillaume/soundsync#118]
Error: You need to wait for AlacEncoder.initPromise before calling this method
    at AlacEncoder.encode (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\utils\alac_vendor\alacEncoder.js:28:19)
    at AirplaySpeaker.pushAudioChunk (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\utils\vendor_integrations\airplay\airplaySpeaker.js:97:26)
    at AirplaySink.handleAudioChunk (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\audio\sinks\airplay_sink.js:52:26)
    at Minipass.AudioSink._handleAudioChunk (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\audio\sinks\audio_sink.js:101:18)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:416:25)
    at Minipass.write (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\audio\sources\audio_source.js:50:70
    at Array.forEach (<anonymous>)
    at Minipass.<anonymous> (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\audio\sources\audio_source.js:50:43)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:416:25)
    at Minipass.write (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at Yallist.<anonymous> (C:\Users\BOSS\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:376:18)

**Comment by geekuillaume** [comment]
Which Airplay device are you using?

**Comment by Yersi88** [comment]
https://www.amazon.co.uk/dp/B084R8N8KD/ 

This is the device, I can play music from iPad with airplay without issues. 

I also tried soundsync version on raspberry pi. I get the error: RTSP on SET_PARAMETER -599. And nothing plays.

**Comment by alexander-cato** [comment]
Same issue for me. Attempting to airplay to Sonos Roam
