### ISSUE TITLE
Error: setMulticastInterface EADDRNOTAVAIL

### ISSUE THREAD

**Issue by msaied56** [geekuillaume/soundsync#137]
Error: setMulticastInterface EADDRNOTAVAIL
    at Socket.setMulticastInterface (dgram.js:818:11)
    at Timeout.that.update [as _onTimeout] (C:\Users\Mike\AppData\Local\Programs\soundsync\resources\app\node_modules\multicast-dns\index.js:141:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by msaied56** [comment]
I wasnt using my computer at the time and this error occurred while it was "locked". Just submitting this bug because the "report on github" option was easy and I want to help.

Thanks,
