### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by talastairb** [geekuillaume/soundsync#18]
Error: 44:48: execution error: An error of type -10810 has occurred. (-10810)

    at ChildProcess.<anonymous> (/Applications/Soundsync.app/Contents/Resources/app/node_modules/applescript/lib/applescript.js:49:13)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by geekuillaume** [comment]
@talastairb thanks for the error report. This seems to be related to the autostart feature. The 10810 error is hard to debug and seems random. I've added code to ignore this error if it happens, the autostart feature won't work if your computer raise this error but everything else will. Can you try again with the last development version? Feel free to reopen the issue if you still have a problem.
