### ISSUE TITLE
 Error trying to run

### ISSUE THREAD

**Issue by NoelR2020** [geekuillaume/soundsync#20]
RuntimeError: abort(Error: Unknown failure). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\rasco\AppData\Local\Programs\soundsync\resources\app\node_modules\wasm-audio-resampler\app\soxr_wasm.js:320:154)
    at process.emit (events.js:228:7)
    at process.EventEmitter.emit (domain.js:475:20)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)

**Comment by geekuillaume** [comment]
@NoelR2020 Can you try again with the last version? I changed a lot of things that could be related

**Comment by geekuillaume** [comment]
No response, I'm closing this. Feel free to reopen if you still experience this issue.
