### ISSUE TITLE
Program crashed on me at startup. MacBook Air Early 2015, macOS version 10.15.6.

### ISSUE THREAD

**Issue by agdamsbo** [geekuillaume/soundsync#27]
TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined
    at validateNumber (internal/validators.js:117:11)
    at Object.getSystemErrorName (util.js:218:3)
    at errnoException (internal/errors.js:463:21)
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writevGeneric (internal/stream_base_commons.js:132:3)
    at Socket._writeGeneric (net.js:774:11)
    at Socket._writev (net.js:783:8)
    at doWrite (_stream_writable.js:433:12)
    at clearBuffer (_stream_writable.js:551:5)
    at Socket.Writable.uncork (_stream_writable.js:329:7)
    at connectionCorkNT (_http_outgoing.js:656:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by geekuillaume** [comment]
I cannot reproduce this. Can you try with the last version (v0.3.9)? What were you doing when it crashed?

**Comment by geekuillaume** [comment]
No response. Closing. Feel free to reopen the issue if you still encounter this issue.
