### ISSUE TITLE
Headless install on non-Raspbian SBC

### ISSUE THREAD

**Issue by LostSoulfly** [geekuillaume/soundsync#35]
I've been trying to figure this one out. I've installed multiple times, verified dependencies, etc.

`/opt/Soundsync/soundsync_electron: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

This shows up in journalctl as well:
![image](https://user-images.githubusercontent.com/9120519/94961587-ecec2e80-04c2-11eb-83ec-a1b4746f4de6.png)

**Comment by geekuillaume** [comment]
I have only tested Raspbian with the provided ARM package. It's possible your distribution doesn't include some packages that are included by default with Raspbian. If you already checked the deps with `sudo apt-get install -f` you can try to install the Chrome or Chromium package for your distribution. These packages have the majority of the same deps than what Electron (which Soundsync uses) requires.

**Comment by LostSoulfly** [comment]
I've tried multiple distributions for my SBC (Rock64) and am never able to get past this same issue. Audio works in general both over HDMI and spdif, as well as through a USB DAC I have, but I can't ever get SoundSync to start. I've even tried compiling/running it with node unsuccessfully.

Any chance you could update the readme with some compiling instructions?

**Comment by geekuillaume** [comment]
To start Soundsync manually you need NodeJS and Git installed then clone this repo `git clone https://github.com/geekuillaume/soundsync`, install the deps `npm install`, build `npm run build` than start it `npm run start`. If you still have the problem, can you send me the logs generated by this command?

**Comment by LostSoulfly** [comment]
Thanks for the quick rundown!

I'm getting closer, slowly but surely..

installed nodejs..
```
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
```
Had to manually install yarn
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```
autoworklet errors:
```
> audioworklet@5.0.2 install /home/dietpi/Desktop/soundsync/app/node_modules/audioworklet
> prebuild-install --target 4 -r napi || npm run build

prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc= platform=linux)

> audioworklet@5.0.2 build /home/dietpi/Desktop/soundsync/app/node_modules/audioworklet
> run-script-os

sh: 1: run-script-os: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! audioworklet@5.0.2 build: `run-script-os`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the audioworklet@5.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dietpi/.npm/_logs/2020-10-12T23_10_51_745Z-debug.log
npm WARN notsup Unsupported engine for node-aead-crypto@2.2.0: wanted: {"node":">4 <10"} (current: {"node":"14.13.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: node-aead-crypto@2.2.0
npm WARN soundsync@0.4.2-dev No repository field.
npm WARN soundsync@0.4.2-dev license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 (node_modules/node-aead-crypto):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 preinstall: `node lib/preinstall.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! audioworklet@5.0.2 install: `prebuild-install --target 4 -r napi || npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the audioworklet@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dietpi/.npm/_logs/2020-10-12T23_10_54_564Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soundsync@0.4.2-dev postinstall: `cd app && (yarn || npm install)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soundsync@0.4.2-dev postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dietpi/.npm/_logs/2020-10-12T23_10_54_897Z-debug.log
```

And here's the tail of the log:
```
45 silly build soundsync@0.4.2-dev
46 info linkStuff soundsync@0.4.2-dev
47 silly linkStuff soundsync@0.4.2-dev has /home/dietpi/Desktop as its parent node_modules
48 silly install soundsync@0.4.2-dev
49 info lifecycle soundsync@0.4.2-dev~install: soundsync@0.4.2-dev
50 silly postinstall soundsync@0.4.2-dev                                                                                                                                                                                                     51 info lifecycle soundsync@0.4.2-dev~postinstall: soundsync@0.4.2-dev
52 verbose lifecycle soundsync@0.4.2-dev~postinstall: unsafe-perm in lifecycle true
53 verbose lifecycle soundsync@0.4.2-dev~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dietpi/Desktop/soundsync/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
54 verbose lifecycle soundsync@0.4.2-dev~postinstall: CWD: /home/dietpi/Desktop/soundsync
55 silly lifecycle soundsync@0.4.2-dev~postinstall: Args: [ '-c', 'cd app && (yarn || npm install)' ]
56 timing audit submit Completed in 636ms
57 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 638ms
58 timing audit body Completed in 9ms
59 silly lifecycle soundsync@0.4.2-dev~postinstall: Returned: code: 1  signal: null
60 info lifecycle soundsync@0.4.2-dev~postinstall: Failed to exec postinstall script
61 verbose stack Error: soundsync@0.4.2-dev postinstall: `cd app && (yarn || npm install)`
61 verbose stack Exit status 1
61 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
61 verbose stack     at EventEmitter.emit (events.js:314:20)
61 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
61 verbose stack     at ChildProcess.emit (events.js:314:20)
61 verbose stack     at maybeClose (internal/child_process.js:1047:16)
61 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
62 verbose pkgid soundsync@0.4.2-dev
63 verbose cwd /home/dietpi/Desktop/soundsync
64 verbose Linux 5.8.13-rockchip64
65 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
66 verbose node v14.13.1
67 verbose npm  v6.14.8
68 error code ELIFECYCLE
69 error errno 1
70 error soundsync@0.4.2-dev postinstall: `cd app && (yarn || npm install)`
70 error Exit status 1
```

**Comment by geekuillaume** [comment]
The install process is failing because I didn't include a Arm64 version of `audioworklet`. I've just released a new version with this arch enabled. Can you try pulling and reinstalling the deps with `yarn` ?

**Comment by LostSoulfly** [comment]
It took some more work, but I got it to run!

I did another clone, installed typescript, manually installed webpack and the newest audioworklet, manually installed pulseaudio, did some other stuff..
![image](https://user-images.githubusercontent.com/9120519/95929625-6ffa6800-0d92-11eb-89bc-c277e6178f88.png)

**Comment by LostSoulfly** [comment]
Finally got around to testing it and I'm not able to send any audio to or receive from it. Looks like everything is sent/received out of order and is dropped. I never hear anything.
![image](https://user-images.githubusercontent.com/9120519/96059419-f2029380-0e5b-11eb-8c8a-2c39e0316de7.png)

**Comment by geekuillaume** [comment]
It seems that the audio is not processed quickly enough to be sent to the audio device in the configured latency. I've implemented some optimizations today. Can you test it with the latest commit (https://github.com/geekuillaume/soundsync/commit/bec36ff5914ad321a44c61038185e64681829076)?

**Comment by LostSoulfly** [comment]
Did a `git pull` then `yarn` then `npm run build` then `npm run start`. Sound source is my Windows 10 desktop with a Ryzen 3700X. This SBC is actually faster than a Pi 3, which is why this is so strange. I've also pulled up htop to show CPU and memory usage.

![image](https://user-images.githubusercontent.com/9120519/96191836-e6be6f00-0f12-11eb-9997-daa2b4f4df7b.png)

**Comment by geekuillaume** [comment]
I've found a bug related to the audio synchronization that could lead in silence. Can you again test the last commit ? Sorry for all this but I cannot reproduce the bug and it's way harder to pinpoint the source of the problem.

**Comment by LostSoulfly** [comment]
Just saw the commits and new version, already on it!

**Comment by LostSoulfly** [comment]
It works! You nailed it with that bug fix. I also tried to install the previous version from the deb package with the same x11 error, but at least I can build and run it manually.

Thanks and great work!

![image](https://user-images.githubusercontent.com/9120519/96350288-3de35180-1083-11eb-9f9e-22ac632a89b8.png)




Here's the SBC I'm using: https://www.amazon.com/Iconikal-Rockchip-Computer-Processor-1866MHz/dp/B0868WSTXH

**Comment by geekuillaume** [comment]
Nice :) Does this work with electron (`yarn run start:electron`) ?

**Comment by LostSoulfly** [comment]
Yes, it does appear to work.

![image](https://user-images.githubusercontent.com/9120519/96490246-909d4480-120e-11eb-855f-9d497385bef3.png)

I can get you terminal access if you want to troubleshoot the deb package, just let me know.

**Comment by LostSoulfly** [comment]
This needs more testing and it's probably got some redundant commands but I was able to get SoundSync running with some or all of this. I'm not sure if it will work all in one copy+paste, but it's definitely something for others to go off of when trying to run this on a headless install.

This was used on Armbian_20.08.1_Rock64_focal_legacy_4.4.213.img headless/server install.
If anyone has any input or additional commands to run please let me know!
(I'd run each set of commands at a time -- this is not a bash script)
```
sudo apt-get update
sudo apt-get -y upgrade

#install alsa
sudo apt-get install libasound2 libasound2-plugins alsa-utils alsa-oss

#install pulseaudio
sudo apt-get install pulseaudio pulseaudio-utils

#set group memberships. Change username to yours
#may not be necessary
sudo usermod -aG pulse,pulse-access <username>
sudo usermod -G audio -a <username>

#unmute all sound devices, probably not necessary
for x in `amixer controls  | grep layback` ; do amixer cset "${x}" on ; done

#Set pulseaudio to auto-run when needed otherwise it may not be running at boot
#sudo nano /etc/pulse/client.conf
#remove the ; next to 
#; autospawn = yes
#and save it

#install nodejs
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt-get install -y nodejs

#Install yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt -y install yarn

#install git
sudo apt-get install -y git

#install npm
sudo apt-get -y install npm

#if you get "you have held broken packages" error you can try and run this:
#sudo apt install aptitude
#sudo aptitude install npm

#clone repo to /opt/soundsync
cd /opt
sudo git clone https://github.com/geekuillaume/soundsync

#easy permissions, feel free to lock yours down stronger
sudo chmod -R 777 soundsync
cd soundsync

#install dependencies
npm install

#install webpack if it doesn't install?
#npm install webpack

#install typescript
npm install typescript --save-dev

#run yarn. I guess it's another package manager?
yarn

#run soundsync build script
npm run build

#run soundsync start script
npm run start

#if everything worked, SoundSync should be running!
#ctrl+c to stop it

#can use pm2 to auto-run soundsync
sudo npm install -g pm2

#don't run these as root, but rather your user
#and be sure to still be in /opt/soundsync working dir
pm2 --name SoundSync start npm -- start

#SoundSync should now be running in a daemon.
#To run at startup use this and do as it says.
pm2 startup

#then run this to save the list of running npm processes
pm2 save


```
