### ISSUE TITLE
i found error

### ISSUE THREAD

**Issue by dh2di3oj2** [geekuillaume/soundsync#37]
Error: You need to wait for SoxrResampler.initPromise before calling this method
    at SoxrResampler.processChunk (C:\Users\..\AppData\Local\Programs\soundsync\resources\app\node_modules\wasm-audio-resampler\app\soxr_resampler.js:66:19)
    at AirplaySink.handleAudioChunk (C:\Users\csa..nj\AppData\Local\Programs\soundsync\resources\app\audio\sinks\airplay_sink.js:54:46)
    at Minipass.AudioSink._handleAudioChunk (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\audio\sinks\audio_sink.js:93:18)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (C:\Users\..\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:416:25)
    at Minipass.write (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at C:\Users\...\AppData\Local\Programs\soundsync\resources\app\audio\sources\audio_source.js:50:70
    at Array.forEach (<anonymous>)
    at Minipass.<anonymous> (C:\Users\..\AppData\Local\Programs\soundsync\resources\app\audio\sources\audio_source.js:50:43)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:416:25)
    at Minipass.write (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:162:12)
    at Yallist.<anonymous> (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\index.js:376:18)
    at Yallist.forEach (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\minipass\node_modules\yallist\yallist.js:156:8)

**Comment by geekuillaume** [comment]
Thanks for reporting this. I fixed it in https://github.com/geekuillaume/soundsync/commit/a7d2519aaa909e7255b9cc1f6b289e076c5b2778. I'm going to release a new version with the fix.
