### ISSUE TITLE
error on install of v 4.1

### ISSUE THREAD

**Issue by dh2di3oj2** [geekuillaume/soundsync#38]
Error: Provided outputBuffer is too small: 16 < 3840
    at SoxrResampler.processChunk (C:\Users\...\AppData\Local\Programs\soundsync\resources\app\node_modules\wasm-audio-resampler\app\soxr_resampler.js:99:19)
    at C:\Users\...\AppData\Local\Programs\soundsync\resources\app\utils\audio\chunk_stream.js:237:48
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processTimers (internal/timers.js:489:9)

**Comment by geekuillaume** [comment]
I've made a lot of changes to this part of the code, can you try again with the last version?

**Comment by dh2di3oj2** [comment]
It works great now
TYSM
