### ISSUE TITLE
SoundSync occasionally crashes with Range Error

### ISSUE THREAD

**Issue by estiens** [geekuillaume/soundsync#40]
OS 10.15.6
MBP 2015 - 2.5GhZ Quad-Core I7
16 GB Ram

```
RangeError: offset is out of bounds
    at Uint16Array.set (<anonymous>)
    at CircularTypedArray.set (/Applications/Soundsync.app/Contents/Resources/app/utils/circularTypedArray.js:43:25)
    at CircularTypedArray.setFromWriterPointer (/Applications/Soundsync.app/Contents/Resources/app/utils/circularTypedArray.js:51:14)
    at AirplaySink.handleAudioChunk (/Applications/Soundsync.app/Contents/Resources/app/audio/sinks/airplay_sink.js:65:25)
    at Minipass.AudioSink._handleAudioChunk (/Applications/Soundsync.app/Contents/Resources/app/audio/sinks/audio_sink.js:93:18)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (/Applications/Soundsync.app/Contents/Resources/app/node_modules/minipass/index.js:416:25)
    at Minipass.write (/Applications/Soundsync.app/Contents/Resources/app/node_modules/minipass/index.js:162:12)
    at /Applications/Soundsync.app/Contents/Resources/app/audio/sources/audio_source.js:50:70
    at Array.forEach (<anonymous>)
    at Minipass.<anonymous> (/Applications/Soundsync.app/Contents/Resources/app/audio/sources/audio_source.js:50:43)
    at Minipass.emit (events.js:310:20)
    at Minipass.EventEmitter.emit (domain.js:482:12)
    at Minipass.emit (/Applications/Soundsync.app/Contents/Resources/app/node_modules/minipass/index.js:416:25)
    at Minipass.write (/Applications/Soundsync.app/Contents/Resources/app/node_modules/minipass/index.js:162:12)
```

**Comment by geekuillaume** [comment]
Thanks for your bug report. I've changed a lot of things recently to this part of the code. Can you try again with the last version and tell me if you still have this bug?

**Comment by estiens** [comment]
I have not seen it popup lately, but I will let you know if I see it again!
