### ISSUE TITLE
running on raspberry pi (stretch)

### ISSUE THREAD

**Issue by gingerlime** [geekuillaume/soundsync#45]
After playing around with Soundsync on my mac, I wanted to test it out on my (headless) rpi. I followed the instructions and managed to install it (using apt install -f etc). As far as I can see it's running

```shell
# ps -ef |grep soundsync
root      9272     1  0 08:56 ?        00:00:00 bash /opt/Soundsync/soundsync --configDir /etc/soundsync
root      9282  9272  0 08:56 ?        00:00:00 /opt/Soundsync/soundsync_electron --experimental-wasm-threads /opt/Soundsync/resources/app/index.js --configDir /etc/soundsync
```

But on my browser (on my Mac) it cannot find it... 

Not sure if it's related, but I also noticed that the `/etc/soundsync` folder wasn't created and even after manually creating it, it was empty

Any other tips to troubleshoot ? :)

**Comment by geekuillaume** [comment]
Can you start Soundsync directly from the command line with `/opt/Soundsync/soundsync` and send me the logs?

**Comment by gingerlime** [comment]
Thank you @geekuillaume !

```
 # /opt/Soundsync/soundsync
Error: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /opt/Soundsync/resources/app/node_modules/audioworklet/build/Release/libcubeb.so)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/Soundsync/resources/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Soundsync/resources/app/node_modules/audioworklet/src/index.js:6:56)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
```

**Comment by geekuillaume** [comment]
It seems that Debian Stretch doesn't provide a new enough version of libc. I don't know if I can compile this lib with a previous version. You can try updating to a new version of Debian to fix this.

**Comment by gingerlime** [comment]
Thank you @geekuillaume ! after upgrading it seems to work 👍
