### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by totti4ever** [geekuillaume/soundsync#54]
Hey, have you already thought about providing a docker image for easy setup on home servers? I tried a bit but ran into few problems, which should be solvable, I assume!

```
  soundsync:peer:placeholderForHttpApiJoin_172.17.0.2:6512 Created new peer +0ms
  soundsync:peer:placeholderForHttpApiJoin_172.17.0.2:6512 Cannot connect to peer with initiator http api http initiator error: 409: Connecting to own peer +62ms
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by alexander-cato** [comment]
+1 For this!

**Comment by dustin-richards-was-here** [comment]
If you're still looking for a Docker container, I made one today and came across this issue! It's got a couple small quirks, but nothing huge.

https://github.com/dustin-richards-was-here/soundsync-docker
